#!/bin/sh
wget -O /usr/lib/enigma2/python/Plugins/Extensions/m3u_Pro/m3u_ProM3U/ReMy_IpTvList.m3u "https://github.com/PrivateTr/Zone_enigma/raw/master/roxy"
sleep 1
wget -O /usr/lib/enigma2/python/Plugins/Extensions/m3u_Pro/m3u_ProM3U/XXpremium.m3u "https://github.com/PrivateTr/Zone_enigma/raw/master/roxyplus"
sleep 1
wget -O /tmp/Latin.m3u "https://github.com/PrivateTr/Zone_enigma/raw/master/Latin-04-11-2019.m3u"
sleep 1
wget -O /tmp/iptvcline.m3u "http://iptv.cline.in:80/get.php?username=40crPzTMSd&password=4dgszhlfAI&type=m3u"
sleep 1
wget -O /tmp/localhdTV.m3u "http://localhd.tv:8081/get.php?username=gueguin.cyrille&password=sosXqioS4I&type=m3u"
sleep 1
wget -O /tmp/canadapro1.m3u "http://iptv6.premium-stv.com:25461/get.php?username=sourcecanadapro1&password=4042848025&type=m3u"
sleep 1
wget -O /tmp/ictv19.m3u "http://ictv19.xyz:8000/get.php?username=orlan&password=1234&type=m3u"
sleep 1
wget -O /tmp/turkiapro1source.m3u "http://iptv6.premium-stv.com:25461/get.php?username=turkiapro1source&password=8564164562&type=m3u"
sleep 1
wget -O /tmp/sourceukpro1.m3u "http://iptv6.premium-stv.com:25461/get.php?username=sourceukpro1&password=6256905511&type=m3u"
sleep 1
wget -O /tmp/diaspromedia.m3u "http://diaspromedia.tv/get.php?username=sa6Oa4Iofq&password=MPqXYzmRZ3&type=m3u"
sleep 1
wget -O /tmp/iptv-luxe.m3u "http://iptv-luxe.com:8789/get.php?username=filipemiranda&password=b5sh0Muzb7&type=m3u"
sleep 1
wget -O /tmp/iptv7premium.m3u "http://iptv7.premium-stv.com:25461/get.php?username=GENERALCHA&password=6535709495&type=m3u"
exit 0
